### ISSUE TITLE
Adapting the behaviour of the France Connect authentication method to the new customised sign up form

### ISSUE THREAD

**Issue by luciegrau** [OpenSourcePolitics/decidim-cese#81]
**Describe the issue**
We need to adapt the behaviour of the France Connect authentication method to the customised sign up form. Previously, users authenticated with France Connect filled in their personal data by completing the socio-demographic authorization handler. As we are going to deactivate this authorization, we need to adapt the behaviour of the France Connect authentication so that users who use this method are redirected to the extra fields on the sign up form when they first connect. 

**Expected behaviour**
As an authenticated France Connect user, I am redirected to the additional fields on the sign up form for my first connection only. The fields displayed are as follows: 

- Date of birth (users under 16 must not be able to validate their registration)
- Address
- Zip code
- City
- Checkbox for certifying the accuracy of the data provided
- Checkbox to subscribe to the newsletter
- Checkbox for acceptance of the platform's general terms and conditions

**Comment by Quentinchampenois** [comment]
Closed by #87
