### ISSUE TITLE
SpamBot Detection - Cannot launch in production mode 

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim-cese#9]
On a fresh server install, Rails server or console don't launch in **`production`** mode because of an error from the SpamBot module. 

```
uninitialized constant Decidim::Admin::Rectify (NameError)
```

This error is not present when using `development` mode.

Server : cese.osp.dev
OS : Ubuntu 20.04
NGINX : nginx/1.18.0 (Ubuntu)
Passenger : 6.0.15
ruby : 3.0.2p107

```
/home/mako/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/decidim-spam_detection-964a091ff49c/app/commands/decidim/admin/unblock_user.rb:5:in `<module:Admin>': uninitialized constant Decidim::Admin::Rectify (NameError)
        from /home/mako/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/decidim-spam_detection-964a091ff49c/app/commands/decidim/admin/unblock_user.rb:4:in `<module:Decidim>'
        from /home/mako/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/decidim-spam_detection-964a091ff49c/app/commands/decidim/admin/unblock_user.rb:3:in `<main>'
```

**Comment by Quentinchampenois** [comment]
Issue is probably for the spam-detection module, I will check it

**Comment by armandfardeau** [comment]
It seems that you are pulling the module from Github which is considered a bad practice. Try pulling from Rubygems instead.
